name: Next.js CI Guardian

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

# 🔥 Agregamos la variable de entorno global para forzar Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    name: Typecheck & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 🔥 Actualizamos de 20 a 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Test Build
        run: npm run build